### PR TITLE
Trailers, Trailer Attachments, Shipment Logs and Vehicle Events

### PR DESCRIPTION
**Pull request by BenGardiner**

### CODE REVIEW

**Comment by ujonson** [comment]
When using "commodity" we should probably use NMFC item numbers in the example. An example NMFC item number 15930 is "Bowling Balls,  other than hollow molded plastic, NOI, in packages"

**Comment by ujonson** [comment]
Maybe we should use ProNumber for the shipment rather than commodity. Should inquire with carriers.

**Comment by BenGardiner** [comment]
> Maybe we should use ProNumber for the shipment rather than commodity. Should inquire with carriers.

not resolvable as stated in this review; I created issue #24

**Comment by BenGardiner** [comment]
> Also keep in mind a shipment may contain many different commodities all lumped together. If you really drill down on this it will get a little complicated and I am not sure that we do this justice inside the API as it probably ties into an internal logistics system which is separate from the TSP system.

Could be true. Are you proposing that we 1) delete the field 2) change the field to an array? NB: the field is already an optional field.

**Pull request merged**
