### PR TITLE
Allow HTTP 429 on health status endpoints

### PR DESCRIPTION
**Pull request by derek-zonar**
Proposed change from #118

### CODE REVIEW

**Comment by derek-zonar** [comment]
Updated the responses. Should we also include the Retry-After header?

**Comment by BenGardiner** [comment]
> Updated the responses. Should we also include the Retry-After header?

Yes, that sounds like a good idea

**Comment by derek-zonar** [comment]
> > Updated the responses. Should we also include the Retry-After header?
> 
> Yes, that sounds like a good idea

Added

**Comment by BenGardiner** [comment]
thanks again, @derek-zonar  . I merged these changes, preserving attribution, into a larger set of changes to resolve some conflicts: see pull request #128

**Pull request closed without merging**
